spring:
    application:
        name: spring-ai-functions
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}
            chat:
                options:
                    model: gpt-4
asb:
    aiapp:
        apiNinjasKey: ${API_NINJAS_KEY}